name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev nlohmann-json3-dev
    - name: Set up CMake
      uses: lukka/get-cmake@latest
      with:
        useCloudCache: false
    - name: Remove CMake cache
      run: rm -rf build
    - name: Configure CMake
      run: cmake -S . -B build
    - name: Build
      run: cmake --build build
